name: Deploy Backend to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Execute remote SSH deployment commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/azureuser/Finance-Access-Control-Backend-Standards
            
            git fetch --all
            git reset --hard origin/main
            
            docker compose down
            
            docker compose up -d --build